package com.kai.custom.ui.settings

import androidx.compose.runtime.Immutable
import com.kai.custom.data.BehaviorStyle
import com.kai.custom.data.CharacterType
import com.kai.custom.data.ImportSection
import com.kai.custom.data.LanguageStyle
import com.kai.custom.data.PersonaConfig
import com.kai.custom.data.Service
import com.kai.custom.data.ThemeMode
import com.kai.custom.inference.LocalModel
import com.kai.custom.mcp.PopularMcpServer
import com.kai.custom.skills.RegistrySkillEntry

@Immutable
data class SettingsActions(
    val onSelectTab: (SettingsTab) -> Unit,
    val onAddService: (Service) -> Unit,
    val onRemoveService: (String) -> Unit,
    val onReorderServices: (List<String>) -> Unit,
    val onExpandService: (String?) -> Unit,
    val onChangeApiKey: (String, String) -> Unit,
    val onChangeBaseUrl: (String, String) -> Unit,
    val onSelectModel: (String, String) -> Unit,
    val onToggleTool: (String, Boolean) -> Unit,
    val onSaveSoul: (String) -> Unit,
    val onChangePersonaName: (String) -> Unit,
    val onSwitchPersona: (String) -> Unit,
    val onSavePersona: (PersonaConfig) -> Unit,
    val onDeletePersona: (String) -> Unit,
    val onCreatePersona: (String, BehaviorStyle, LanguageStyle, CharacterType) -> Unit,
    val onToggleDynamicUi: (Boolean) -> Unit,
    val onChangeThemeMode: (ThemeMode) -> Unit,
    val onToggleMemory: (Boolean) -> Unit,
    val onToggleAltMemory: (Boolean) -> Unit,
    val onDeleteMemory: (String) -> Unit,
    val onUpdateMemory: (String, String) -> Unit,
    val onToggleScheduling: (Boolean) -> Unit,
    val onCancelTask: (String) -> Unit,
    val onToggleDaemon: (Boolean) -> Unit,
    val onToggleFloatingBall: (Boolean) -> Unit,
    val onToggleHeartbeat: (Boolean) -> Unit,
    val onChangeHeartbeatInterval: (Int) -> Unit,
    val onChangeHeartbeatActiveHours: (Int, Int) -> Unit,
    val onSaveHeartbeatPrompt: (String) -> Unit,
    val onChangeHeartbeatService: (String?) -> Unit,
    val onRefreshHeartbeat: () -> Unit,
    val onToggleEmail: (Boolean) -> Unit,
    val onRemoveEmailAccount: (String) -> Unit,
    val onChangeEmailPollInterval: (Int) -> Unit,
    val onRefreshEmailAccount: (String) -> Unit,
    val onToggleSms: (Boolean) -> Unit,
    val onChangeSmsPollInterval: (Int) -> Unit,
    val onRefreshSms: () -> Unit,
    val onToggleSmsSend: (Boolean) -> Unit,
    val onToggleNotifications: (Boolean) -> Unit,
    val onOpenNotificationListenerSettings: () -> Unit,
    val onOpenTtsSettings: () -> Unit,
    val onClearPendingNotifications: () -> Unit,
    val onToggleShizuku: (Boolean) -> Unit,
    val onOpenShizukuPermission: () -> Unit,
    val onToggleRoot: (Boolean) -> Unit,
    val onToggleDebugApi: (Boolean) -> Unit,
    val onToggleDebugEndpoint: (Boolean) -> Unit,
    val onToggleFreeFallback: (Boolean) -> Unit,
    val onToggleWakeWord: (Boolean) -> Unit,
    val onChangeWakeWordPhrase: (String) -> Unit,
    val onChangePreferredLanguage: (String) -> Unit,
    val onChangeWakeWordMode: (String) -> Unit,
    val onEnrollWakeWord: () -> Unit,
    val onCapturePttTrigger: () -> Unit,
    val onClearPttTrigger: () -> Unit,
    val onPickSafWorkDir: (String) -> Unit,
    val onClearSafWorkDir: () -> Unit,
    val onChangeUiScale: (Float) -> Unit,
    val onAddMcpServer: (String, String, Map<String, String>) -> Unit,
    val onRemoveMcpServer: (String) -> Unit,
    val onToggleMcpServer: (String, Boolean) -> Unit,
    val onRefreshMcpServer: (String) -> Unit,
    val onUpdateMcpApiKey: (String, String) -> Unit,
    val onShowAddMcpServerDialog: (Boolean) -> Unit,
    val onAddPopularMcpServer: (PopularMcpServer) -> Unit,
    val onDownloadLocalModel: (LocalModel) -> Unit,
    val onCancelLocalModelDownload: () -> Unit,
    val onDeleteLocalModel: (String) -> Unit,
    val onChangeModelContextTokens: (String, Int) -> Unit,
    val onChangeModelMaxTokens: (String, Int) -> Unit,
    val onChangeModelTemperature: (String, Float) -> Unit,
    val onChangeLocalStyleInstruction: (String) -> Unit,
    val onChangeLocalModelFullPrompt: (Boolean) -> Unit,
    val onChangeModelTopK: (String, Int) -> Unit,
    val onChangeModelTopP: (String, Float) -> Unit,
    val onChangeModelGpuLayers: (String, Int) -> Unit = { _, _ -> },
    val onImportLocalModel: (ByteArray, String) -> Unit,
    val onImportPlatformFileComplete: (com.kai.custom.inference.ImportedModel) -> Unit,
    val onImportComplete: () -> Unit,
    val onExportSettings: (Set<ImportSection>) -> String,
    val onPrepareExport: () -> Map<ImportSection, String?>,
    val onImportSettings: (ByteArray, Set<ImportSection>, Boolean) -> ImportResult,
    val onUndoDelete: () -> Unit,
    val onExportDimension: suspend () -> ByteArray,
    val onImportDimension: (ByteArray) -> Unit,
    val onInstallGitHub: (String) -> Unit,
    val onInstallBrowsed: (RegistrySkillEntry) -> Unit,
    val onUninstallSkill: (String) -> Unit,
    val onBrowseMarketplaceSkills: () -> Unit,
) {
    companion object {
        val NoOp = SettingsActions(
            onSelectTab = {},
            onAddService = {},
            onRemoveService = {},
            onReorderServices = {},
            onExpandService = {},
            onChangeApiKey = { _, _ -> },
            onChangeBaseUrl = { _, _ -> },
            onSelectModel = { _, _ -> },
            onToggleTool = { _, _ -> },
            onSaveSoul = {},
            onChangePersonaName = {},
            onSwitchPersona = {},
            onSavePersona = {},
            onDeletePersona = {},
            onCreatePersona = { _, _, _, _ -> },
            onToggleDynamicUi = {},
            onChangeThemeMode = {},
            onToggleMemory = {},
            onToggleAltMemory = {},
            onDeleteMemory = {},
            onUpdateMemory = { _, _ -> },
            onToggleScheduling = {},
            onCancelTask = {},
            onToggleDaemon = {},
            onToggleFloatingBall = {},
            onToggleHeartbeat = {},
            onChangeHeartbeatInterval = {},
            onChangeHeartbeatActiveHours = { _, _ -> },
            onSaveHeartbeatPrompt = {},
            onChangeHeartbeatService = {},
            onRefreshHeartbeat = {},
            onToggleEmail = {},
            onRemoveEmailAccount = {},
            onChangeEmailPollInterval = {},
            onRefreshEmailAccount = {},
            onToggleSms = {},
            onChangeSmsPollInterval = {},
            onRefreshSms = {},
            onToggleSmsSend = {},
            onToggleNotifications = {},
            onOpenNotificationListenerSettings = {},
            onOpenTtsSettings = {},
            onClearPendingNotifications = {},
            onToggleShizuku = {},
            onOpenShizukuPermission = {},
            onToggleRoot = {},
            onToggleDebugApi = {},
            onToggleDebugEndpoint = {},
            onToggleFreeFallback = {},
            onToggleWakeWord = {},
            onChangeWakeWordPhrase = {},
            onChangePreferredLanguage = {},
            onChangeWakeWordMode = {},
            onEnrollWakeWord = {},
            onCapturePttTrigger = {},
            onClearPttTrigger = {},
            onPickSafWorkDir = {},
            onClearSafWorkDir = {},
            onChangeUiScale = {},
            onAddMcpServer = { _, _, _ -> },
            onRemoveMcpServer = {},
            onToggleMcpServer = { _, _ -> },
            onRefreshMcpServer = {},
            onUpdateMcpApiKey = { _, _ -> },
            onShowAddMcpServerDialog = {},
            onAddPopularMcpServer = {},
            onDownloadLocalModel = {},
            onCancelLocalModelDownload = {},
            onDeleteLocalModel = {},
            onChangeModelContextTokens = { _, _ -> },
            onChangeModelMaxTokens = { _, _ -> },
            onChangeModelTemperature = { _, _ -> },
            onChangeLocalStyleInstruction = {},
            onChangeLocalModelFullPrompt = {},
            onChangeModelTopK = { _, _ -> },
            onChangeModelTopP = { _, _ -> },
            onImportLocalModel = { _, _ -> },
            onImportPlatformFileComplete = {},
            onImportComplete = {},
            onExportSettings = { _ -> "" },
            onPrepareExport = { emptyMap() },
            onImportSettings = { _, _, _ -> ImportResult.Failure },
            onUndoDelete = {},
            onExportDimension = { ByteArray(0) },
            onImportDimension = {},
            onInstallGitHub = {},
            onInstallBrowsed = {},
            onUninstallSkill = {},
            onBrowseMarketplaceSkills = {},
        )
    }
}
